apiVersion: apps/v1
kind: Deployment
metadata:
  name: fenixgate
  namespace: fg
  labels:
    app: fenixgate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fenixgate
  template:
    metadata:
      labels:
        app: fenixgate
    spec:
      containers:
        - name: fenixgate
          image: fenixgate:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
